### ISSUE TITLE
Unsupported number of constructor arguments

### ISSUE THREAD

**Issue by Ryde-G** [PsuAeroacoustics/OpenCOPTER#4]
Hi,

I am having issues with the code once I get to the python3 example.py

I have had no other issues downloading and using the rest and have gotten no error messages.

When I try to use python3 example.py I get the following message:
/home/ryde/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
requested_elements:  45  actual elements:  48
Traceback (most recent call last):
  File "/home/ryde/OpenCOPTER/examples/python/example.py", line 98, in <module>
    aircraft.rotors = [build_rotor(r_idx) for r_idx in range(num_rotors)]
  File "/home/ryde/OpenCOPTER/examples/python/example.py", line 98, in <listcomp>
    aircraft.rotors = [build_rotor(r_idx) for r_idx in range(num_rotors)]
  File "/home/ryde/OpenCOPTER/examples/python/example.py", line 94, in build_rotor
    rotor.blades = [build_blade(b_idx) for b_idx in range(num_blades)]
  File "/home/ryde/OpenCOPTER/examples/python/example.py", line 94, in <listcomp>
    rotor.blades = [build_blade(b_idx) for b_idx in range(num_blades)]
  File "/home/ryde/OpenCOPTER/examples/python/example.py", line 69, in build_blade
    blade = BladeGeometry(
TypeError: Unsupported number of constructor arguments.

I would appreciate help figuring this out!

**Comment by Rob-Rau** [comment]
Thanks for reaching out! I had been a bit derelict in updating that example as time progressed. I just pushed a commit to the development branch that fixes that example so it works again.

**Comment by Ryde-G** [comment]
Thank you so much!
