### ISSUE TITLE
Example issue

### ISSUE THREAD

**Issue by VatsLadhani** [PsuAeroacoustics/OpenCOPTER#6]
Hello, I have built the software and was trying to run the example by going into examples -> python and running the command python3 example.py
I got an error saying  line 8, in <module>
    from libopencopter import *
ImportError: dynamic module does not define module export function (PyInit_libopencopter)

I tried to check if it had the necessary export function by using 
nm -D /home/vats/OpenCOPTER/libopencopter.so | grep PyInit
and got no result. Needed some assistance to figure it out as I am quite new to this.

**Comment by Rob-Rau** [comment]
Hello Vats,

Thanks for reaching out. It looks to me like you did not compile opencopter with python suppoert enabled. To do this, you need to run the dub command with -c library-python<xxx> where <xxx> is the version of python you're building for. For example, python 3.10 support is build using -c library-python310.

If you don't want vtk support, then the configuration parameter looks like -c library-python<xxx>-novtk.

These options are outlined here: https://github.com/PsuAeroacoustics/OpenCOPTER?tab=readme-ov-file#configurations--c

Let me know if this gets you unstuck

**Comment by VatsLadhani** [comment]
The examples/pyhton/example.py runs now. However, after 5000 iterations it shows me the error
Traceback (most recent call last):
  File "/home/OpenCOPTER/examples/python/example.py", line 209, in <module>
    write_rotor_vtu("rotor", iteration, 0, vtk_rotor, ac_state.rotor_states[0], ac_input_state.rotor_inputs[0], aircraft.rotors[0])
TypeError: functiontakesexactly 6 arguments (7 given)

I tried changing the input arguments by removing the 0 in that line and running it again.
It gave me this error

Traceback (most recent call last):
  File "/home/OpenCOPTER/examples/python/example.py", line 209, in <module>
    write_rotor_vtu("rotor", iteration, vtk_rotor, ac_state.rotor_states[0], ac_input_state.rotor_inputs[0], aircraft.rotors[0])
RuntimeError: D Exception:
pyd.make_object.PydConversionException@dependencies/pyd/infrastructure/pyd/make_object.d(706): Couldn't convert Python type 'VtkRotor' to D type 'ulong'

I am not sure what could be causing this error

**Comment by VatsLadhani** [comment]
That solved it thank you. 

One more thing, the code in the examples/python/example.py gives an error after 5000 iterations.

Traceback (most recent call last):
  File "/home/OpenCOPTER/examples/python/example.py", line 209, in <module>
    write_rotor_vtu("rotor", iteration, 0, vtk_rotor, ac_state.rotor_states[0], ac_input_state.rotor_inputs[0], aircraft.rotors[0])
TypeError: functiontakesexactly 6 arguments (7 given)

I changed the line to  write_rotor_vtu("rotor", iteration, 0, vtk_rotor, ac_state.rotor_states[0], aircraft.rotors[0]) and it seems to run fine.

**Comment by takshaysurana07** [comment]
> Thanks for reaching out. It looks to me like you did not compile opencopter with python suppoert enabled. To do this, you need to run the dub command with -c library-python where is the version of python you're building for. For example, python 3.10 support is build using -c library-python310.

I have been facing the same problem for quite some time with python 3.12.3 and I tried your solution but it asked me to add python312 in the dub.json file and kxml dependency and a few other things. But when i try to  do dub build it shows me errors in math/package.d and math/trigonometry.d. Please help me out at the earliest, I am quite new at this

**Comment by Rob-Rau** [comment]
The underlying python binding library needs to be updated for python 3.12. I'll try to get around to this in the coming days

**Comment by takshaysurana07** [comment]
> The underlying python binding library needs to be updated for python 3.12. I'll try to get around to this in the coming days

I installed python 3.10 to see if it works, I still get errors when i do dub -c library-python310. This is the last command before running example.py. What do I do? It shows errors in matplotlib-d.
